import RootProvider from "@/global/providers/root.provider"
import "./globals.css"
import { Inter } from "next/font/google"
import Navbar from "@/global/components/navbar.component"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <RootProvider>
        <body className={`${inter.className}`}>
          <Navbar />
          {children}
        </body>
      </RootProvider>
    </html>
  )
}
